### ISSUE TITLE
Broken on 1.3.2

### ISSUE THREAD

**Issue by bilalaslam** [angular-ui/ui-ace#73]
ui.ace was working on angular-1.3.0-beta.9 but is broken on 1.3.2 with this error:

```
TypeError: Cannot read property '$formatters' of null
    at link (http://localhost:3041/vendor/angular-ui-ace/ui-ace.js:171:18)
    at invokeLinkFn (http://localhost:3041/vendor/angular/angular.js:8125:9)
    at nodeLinkFn (http://localhost:3041/vendor/angular/angular.js:7637:11)
    at compositeLinkFn (http://localhost:3041/vendor/angular/angular.js:6993:13)
    at nodeLinkFn (http://localhost:3041/vendor/angular/angular.js:7632:24)
    at compositeLinkFn (http://localhost:3041/vendor/angular/angular.js:6993:13)
    at compositeLinkFn (http://localhost:3041/vendor/angular/angular.js:6996:13)
    at publicLinkFn (http://localhost:3041/vendor/angular/angular.js:6872:30)
    at compile (http://localhost:3041/vendor/angular-ui-router/release/angular-ui-router.js:2805:9)
    at invokeLinkFn (http://localhost:3041/vendor/angular/angular.js:8125:9) <div ui-ace="{
          useWrapMode : true,
          showGutter: false,
          theme:'twilight',
          mode: 'sql',
          onLoad: aceLoaded,
          onChange: aceChanged
        }" class=" ace_editor ace-tm"> 
```

**Comment by ebuildy** [comment]
This is because ng-model is null and function angular.isDefined(ng-model) returns true! I am proposing a fix.
